### ISSUE TITLE
[Bug] [Mac] Need to put the string with the @ prefix in quotes

### ISSUE THREAD

**Issue by tangaac** [ali77gh/bake-rs#3]
## Issue

This yaml didn't work as expected.
~~~yaml
tasks:
  - name: call
    commands:
    - @this.hello

  - name: hello
    commands: 
      - echo hello world
~~~

~~~bash
> bake call
 ▶ Bake version: 1.2.0

found character that cannot start any token at line 4 column 7, while scanning for the next token
~~~

## Solution
Put the string with the @ prefix in "" or '', then it works.
```yaml
tasks:
  - name: call
    commands:
    - "@this.hello"

  - name: hello
    commands: 
      - echo hello world
```
```bash
> bake call
 ▶ Bake version: 1.2.0

  ▶ Bake : task 'call' is running...
  ▶ Bake : task 'hello' is running...
  ▶ Bake : running command => 'echo hello world'
hello world
  ▶ Bake : Task 'hello' finished successfully. time: 6ms
  ▶ Bake : Task 'call' finished successfully. time: 6ms
```

## My Found
I found the error occurs in `serde_yaml::from_str`.
I'm not sure if this error also occurred in Windows & Linux.  
If this solution can also work on Windows & Linux, we should update the  documentation.
